name: Upload to Harvard Dataverse

on:
  release:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Send repo to Dataverse
        uses: IQSS/dataverse-uploader@v1.6
        with:
          DATAVERSE_TOKEN: ${{ secrets.DATAVERSE_TOKEN }}
          DATAVERSE_SERVER: https://dataverse.harvard.edu
          DATAVERSE_DATASET_DOI: doi:10.7910/DVN/T0630D 
          # DELETE: True   # default True; see note below
          # PUBLISH: False # default False; see note below
